"""create learners

Revision ID: 3272c419c186
Revises: 29dc2f5a9c4f
Create Date: 2026-09-22 17:07:08.456076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3272c419c186'
down_revision: Union[str, Sequence[str], None] = '29dc2f5a9c4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('birth_date', sa.DateTime(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learners_cpf'), 'learners', ['cpf'], unique=False)
    op.create_index(op.f('ix_learners_id'), 'learners', ['id'], unique=False)
    op.create_index(op.f('ix_learners_institution_id'), 'learners', ['institution_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_learners_institution_id'), table_name='learners')
    op.drop_index(op.f('ix_learners_id'), table_name='learners')
    op.drop_index(op.f('ix_learners_cpf'), table_name='learners')
    op.drop_table('learners')
    # ### end Alembic commands ###
