import { Student, Turma, AuditLog, SystemUser } from './types';

export const INITIAL_TURMAS: Turma[] = [
  {
    id: 'turma-ti-01',
    codigo: 'DS-2026.1-A',
    nomeCurso: 'Técnico em Desenvolvimento de Sistemas',
    periodo: '2026.1 - Manhã',
    totalAlunos: 28,
    conformidadeMedia: 89,
    alunosEmRisco: 2,
    alunosRegulares: 24,
  },
  {
    id: 'turma-adm-02',
    codigo: 'ADM-2026.1-B',
    nomeCurso: 'Técnico em Administração & RH',
    periodo: '2026.1 - Noite',
    totalAlunos: 32,
    conformidadeMedia: 76,
    alunosEmRisco: 6,
    alunosRegulares: 21,
  },
  {
    id: 'turma-log-03',
    codigo: 'LOG-2025.2-T',
    nomeCurso: 'Técnico em Logística Integrada',
    periodo: '2025.2 - Tarde',
    totalAlunos: 24,
    conformidadeMedia: 94,
    alunosEmRisco: 1,
    alunosRegulares: 22,
  },
];

export const INITIAL_SYSTEM_USERS: SystemUser[] = [
  {
    id: 'usr-001',
    nome: 'Lucas Gabriel da Silva',
    email: 'lucas.gabriel@empresa-tech.com.br',
    role: 'ESTUDANTE',
    cargo: 'Aprendiz Desenvolvedor Frontend',
    status: 'ATIVO',
    ultimoAcesso: 'Hoje às 14:30',
  },
  {
    id: 'usr-002',
    nome: 'Profª. Mariana Alcantara',
    email: 'mariana.coordenacao@etec.sp.gov.br',
    role: 'COORDENADOR',
    cargo: 'Coordenadora Acadêmica de Cursos Técnicos',
    status: 'ATIVO',
    ultimoAcesso: 'Hoje às 15:10',
  },
  {
    id: 'usr-003',
    nome: 'Camila Peixoto',
    email: 'camila.rh@techcorp.com.br',
    role: 'COORDENADOR',
    cargo: 'Gestora de RH & Contratos de Estágio',
    status: 'ATIVO',
    ultimoAcesso: 'Ontem às 17:40',
  },
  {
    id: 'usr-004',
    nome: 'Administrador Geral DocFlow',
    email: 'admin@docflow.security',
    role: 'SUPERADMIN',
    cargo: 'Super Administrador do Sistema',
    status: 'ATIVO',
    ultimoAcesso: 'Agora mesmo',
  },
];

export const CURRENT_STUDENT: Student = {
  id: 'std-001',
  nome: 'Lucas Gabriel da Silva',
  cpf: '458.912.308-44',
  email: 'lucas.gabriel@empresa-tech.com.br',
  matricula: '2026-DS-0142',
  turmaId: 'turma-ti-01',
  turmaNome: 'DS-2026.1-A — Desenvolvimento de Sistemas',
  curso: 'Técnico em Desenvolvimento de Sistemas',
  empresa: 'TechCorp Soluções Digitais S.A.',
  percentualConformidade: 80,
  nivelRisco: 'MEDIO',
  statusGeral: 'PENDENTE',
  documentos: [
    {
      id: 'doc-rg-01',
      tipo: 'RG',
      nomeExibicao: 'Carteira de Identidade (RG)',
      descricao: 'Frente e verso nítidos com órgão emissor e foto visível.',
      obrigatorio: true,
      status: 'APROVADO',
      nomeArquivoOriginal: 'rg_lucas_silva_2026.pdf',
      storageUuid: 'doc_5b1a9f4c-7832-4d1e-9a10-2fbc1a0e19a1.pdf',
      tamanhoBytes: 1845200,
      mimeType: 'application/pdf',
      fileHashSha256: '9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08',
      dataEnvio: '2026-08-15T10:20:00Z',
      aprovadoPor: 'Profª. Mariana Alcantara (Coordenação)',
      dataAvaliacao: '2026-08-16T14:10:00Z',
      conteudoSensivelSimulado: {
        rgNumero: '52.341.890-X',
        rgFiliacaoMae: 'Maria Helena da Silva',
        rgFiliacaoPai: 'Antônio Carlos da Silva',
        rgDataNascimento: '14/05/2005',
        cpfNumero: '458.912.308-44',
      },
    },
    {
      id: 'doc-cpf-02',
      tipo: 'CPF',
      nomeExibicao: 'Comprovante de Inscrição no CPF',
      descricao: 'Comprovante da Receita Federal ou CNH/RG contendo o CPF regular.',
      obrigatorio: true,
      status: 'APROVADO',
      nomeArquivoOriginal: 'comprovante_cpf_receita.pdf',
      storageUuid: 'doc_882cb0ef-3392-4f11-9a72-88efca110293.pdf',
      tamanhoBytes: 524100,
      mimeType: 'application/pdf',
      fileHashSha256: '5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8',
      dataEnvio: '2026-08-15T10:22:00Z',
      aprovadoPor: 'Profª. Mariana Alcantara (Coordenação)',
      dataAvaliacao: '2026-08-16T14:12:00Z',
      conteudoSensivelSimulado: {
        cpfNumero: '458.912.308-44',
      },
    },
    {
      id: 'doc-res-03',
      tipo: 'COMPROVANTE_RESIDENCIA',
      nomeExibicao: 'Comprovante de Residência Atualizado',
      descricao: 'Conta de água, luz ou telefone emitida nos últimos 90 dias.',
      obrigatorio: true,
      status: 'APROVADO',
      nomeArquivoOriginal: 'conta_energia_julho.pdf',
      storageUuid: 'doc_102fe8ca-45aa-4399-bfb1-33dc9019aa99.pdf',
      tamanhoBytes: 890450,
      mimeType: 'application/pdf',
      fileHashSha256: '4b227777d4dd1fc61c6f884f48641d02b4d121d3fd328cb08b5531fcacdabf8a',
      dataEnvio: '2026-08-15T10:25:00Z',
      aprovadoPor: 'Profª. Mariana Alcantara (Coordenação)',
      dataAvaliacao: '2026-08-16T14:15:00Z',
      conteudoSensivelSimulado: {
        enderecoCompleto: 'Rua das Palmeiras, 1420 - Bloco B, Apto 32 - São Paulo/SP',
      },
    },
    {
      id: 'doc-mat-04',
      tipo: 'COMPROVANTE_MATRICULA',
      nomeExibicao: 'Comprovante de Matrícula Semestral',
      descricao: 'Declaração oficial da instituição de ensino com período letivo atual.',
      obrigatorio: true,
      status: 'EM_ANALISE',
      nomeArquivoOriginal: 'declaracao_matricula_2026_2.pdf',
      storageUuid: 'doc_284102ba-7711-44aa-9c44-eefc91024501.pdf',
      tamanhoBytes: 1240100,
      mimeType: 'application/pdf',
      fileHashSha256: 'ef2d127de37b942baad06145e54b0c619a1f22327b2ebbcfbec78f5564afe39d',
      dataEnvio: '2026-08-30T16:45:00Z',
      validadeAte: '2026-09-15',
      diasParaVencer: 14,
      conteudoSensivelSimulado: {
        semestreAtual: '2º Semestre Letivo / 2026',
        instituicaoEnsino: 'Escola Técnica Estadual São Paulo - ETEC',
      },
    },
    {
      id: 'doc-tce-05',
      tipo: 'CONTRATO_TCE',
      nomeExibicao: 'Contrato de Estágio / Aprendizagem (TCE)',
      descricao: 'Termo assinado pela Instituição, Empresa Concedente e Aprendiz/Estagiário.',
      obrigatorio: true,
      status: 'PENDENTE',
      conteudoSensivelSimulado: {
        empresaConcedente: 'TechCorp Soluções Digitais S.A.',
        valorBolsa: 'R$ 1.850,00 + Auxílio Transporte',
      },
    },
  ],
};

export const INITIAL_STUDENTS: Student[] = [
  CURRENT_STUDENT,
  {
    id: 'std-002',
    nome: 'Beatriz Vasconcelos Ramos',
    cpf: '381.724.890-12',
    email: 'beatriz.ramos@fintechbrazil.com',
    matricula: '2026-DS-0145',
    turmaId: 'turma-ti-01',
    turmaNome: 'DS-2026.1-A — Desenvolvimento de Sistemas',
    curso: 'Técnico em Desenvolvimento de Sistemas',
    empresa: 'Fintech Brasil Inovações',
    percentualConformidade: 100,
    nivelRisco: 'BAIXO',
    statusGeral: 'REGULAR',
    documentos: [
      {
        id: 'doc-b1',
        tipo: 'RG',
        nomeExibicao: 'Carteira de Identidade (RG)',
        descricao: 'RG com foto',
        obrigatorio: true,
        status: 'APROVADO',
        nomeArquivoOriginal: 'rg_beatriz_2026.pdf',
        storageUuid: 'doc_1111-2222-3333.pdf',
        fileHashSha256: 'a1b2c3d4e5f67890123456789abcdef0123456789abcdef0123456789abcdef0',
        conteudoSensivelSimulado: {
          rgNumero: '48.912.001-9',
          rgFiliacaoMae: 'Sandra Regina Ramos',
          rgFiliacaoPai: 'Paulo Roberto Ramos',
        },
      },
      {
        id: 'doc-b2',
        tipo: 'CPF',
        nomeExibicao: 'CPF',
        descricao: 'Cartão CPF',
        obrigatorio: true,
        status: 'APROVADO',
        nomeArquivoOriginal: 'cpf_beatriz.pdf',
        storageUuid: 'doc_4444-5555-6666.pdf',
        fileHashSha256: 'b2c3d4e5f67890123456789abcdef0123456789abcdef0123456789abcdef01',
      },
      {
        id: 'doc-b3',
        tipo: 'COMPROVANTE_RESIDENCIA',
        nomeExibicao: 'Comprovante Residência',
        descricao: 'Conta residencial',
        obrigatorio: true,
        status: 'APROVADO',
        nomeArquivoOriginal: 'conta_luz_beatriz.pdf',
        storageUuid: 'doc_7777-8888-9999.pdf',
        fileHashSha256: 'c3d4e5f67890123456789abcdef0123456789abcdef0123456789abcdef012',
      },
      {
        id: 'doc-b4',
        tipo: 'COMPROVANTE_MATRICULA',
        nomeExibicao: 'Comprovante Matrícula',
        descricao: 'Matrícula 2026.2',
        obrigatorio: true,
        status: 'APROVADO',
        validadeAte: '2026-12-31',
        diasParaVencer: 120,
        nomeArquivoOriginal: 'matricula_etec_beatriz.pdf',
        storageUuid: 'doc_aaaa-bbbb-cccc.pdf',
        fileHashSha256: 'd4e5f67890123456789abcdef0123456789abcdef0123456789abcdef0123',
      },
      {
        id: 'doc-b5',
        tipo: 'CONTRATO_TCE',
        nomeExibicao: 'Contrato TCE',
        descricao: 'Termo assinado',
        obrigatorio: true,
        status: 'APROVADO',
        nomeArquivoOriginal: 'tce_assinado_fintech.pdf',
        storageUuid: 'doc_dddd-eeee-ffff.pdf',
        fileHashSha256: 'e5f67890123456789abcdef0123456789abcdef0123456789abcdef01234',
      },
    ],
  },
  {
    id: 'std-003',
    nome: 'Carlos Eduardo Nogueira',
    cpf: '298.410.551-90',
    email: 'carlos.nogueira@logistix.com.br',
    matricula: '2026-DS-0149',
    turmaId: 'turma-ti-01',
    turmaNome: 'DS-2026.1-A — Desenvolvimento de Sistemas',
    curso: 'Técnico em Desenvolvimento de Sistemas',
    empresa: 'Logistix Transportes & Cargas',
    percentualConformidade: 40,
    nivelRisco: 'CRITICO',
    statusGeral: 'ALERTA_CRITICO',
    documentos: [
      {
        id: 'doc-c1',
        tipo: 'RG',
        nomeExibicao: 'Carteira de Identidade (RG)',
        descricao: 'RG',
        obrigatorio: true,
        status: 'APROVADO',
        nomeArquivoOriginal: 'rg_carlos.jpg',
        storageUuid: 'doc_c1-uuid.jpg',
      },
      {
        id: 'doc-c2',
        tipo: 'CPF',
        nomeExibicao: 'CPF',
        descricao: 'CPF',
        obrigatorio: true,
        status: 'APROVADO',
        nomeArquivoOriginal: 'cpf_carlos.pdf',
        storageUuid: 'doc_c2-uuid.pdf',
      },
      {
        id: 'doc-c3',
        tipo: 'COMPROVANTE_RESIDENCIA',
        nomeExibicao: 'Comprovante Residência',
        descricao: 'Residência',
        obrigatorio: true,
        status: 'RECUSADO',
        justificativaRecusa: 'Documento ilegível e emitido há mais de 180 dias (fora do padrão de 90 dias). Envie comprovante recente.',
        dataAvaliacao: '2026-08-28T11:00:00Z',
        aprovadoPor: 'Coordenação Acadêmica',
      },
      {
        id: 'doc-c4',
        tipo: 'COMPROVANTE_MATRICULA',
        nomeExibicao: 'Comprovante Matrícula',
        descricao: 'Matrícula Semestral',
        obrigatorio: true,
        status: 'EXPIRADO',
        validadeAte: '2026-08-20',
        diasParaVencer: -12,
        justificativaRecusa: 'Matrícula do 1º semestre expirada. Risco iminente de cancelamento de estágio.',
      },
      {
        id: 'doc-c5',
        tipo: 'CONTRATO_TCE',
        nomeExibicao: 'Contrato TCE',
        descricao: 'Contrato TCE',
        obrigatorio: true,
        status: 'PENDENTE',
      },
    ],
  },
  {
    id: 'std-004',
    nome: 'Juliana Mendes de Castro',
    cpf: '519.832.109-03',
    email: 'juliana.castro@varejobrasil.com.br',
    matricula: '2026-ADM-088',
    turmaId: 'turma-adm-02',
    turmaNome: 'ADM-2026.1-B — Administração & RH',
    curso: 'Técnico em Administração & RH',
    empresa: 'Grupo Varejo Nacional',
    percentualConformidade: 60,
    nivelRisco: 'MEDIO',
    statusGeral: 'PENDENTE',
    documentos: [
      { id: 'doc-j1', tipo: 'RG', nomeExibicao: 'RG', descricao: 'RG', obrigatorio: true, status: 'APROVADO' },
      { id: 'doc-j2', tipo: 'CPF', nomeExibicao: 'CPF', descricao: 'CPF', obrigatorio: true, status: 'APROVADO' },
      { id: 'doc-j3', tipo: 'COMPROVANTE_RESIDENCIA', nomeExibicao: 'Comprovante Residência', descricao: 'Residência', obrigatorio: true, status: 'APROVADO' },
      { id: 'doc-j4', tipo: 'COMPROVANTE_MATRICULA', nomeExibicao: 'Comprovante Matrícula', descricao: 'Matrícula', obrigatorio: true, status: 'EM_ANALISE' },
      { id: 'doc-j5', tipo: 'CONTRATO_TCE', nomeExibicao: 'Contrato TCE', descricao: 'TCE', obrigatorio: true, status: 'PENDENTE' },
    ],
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log-001',
    timestampUtc: '2026-09-01T15:42:10Z',
    userId: 'usr-coord-01',
    userNome: 'Profª. Mariana Alcantara',
    userRole: 'COORDENADOR',
    action: 'DOCUMENT_APPROVAL',
    resourceId: 'doc-rg-01',
    resourceTipo: 'Documento: RG (Lucas Gabriel da Silva)',
    ipAddress: '189.45.112.44',
    status: 'SUCCESS',
    detalhes: 'Documento aprovado após verificação formal de autenticidade.',
    sha256Hash: '9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08',
    storageUuid: 'doc_5b1a9f4c-7832-4d1e-9a10-2fbc1a0e19a1.pdf',
  },
  {
    id: 'log-002',
    timestampUtc: '2026-09-01T14:18:22Z',
    userId: 'usr-std-001',
    userNome: 'Lucas Gabriel da Silva',
    userRole: 'ESTUDANTE',
    action: 'SYSTEM_MAGIC_BYTES_VALIDATION',
    resourceId: 'doc-mat-04',
    resourceTipo: 'Upload: Comprovante de Matrícula',
    ipAddress: '177.132.89.201',
    status: 'SUCCESS',
    detalhes: 'Magic bytes confirmados (0x25 0x50 0x44 0x46 - PDF). Hash SHA-256 gerado e UUID atribuído.',
    sha256Hash: 'ef2d127de37b942baad06145e54b0c619a1f22327b2ebbcfbec78f5564afe39d',
    storageUuid: 'doc_284102ba-7711-44aa-9c44-eefc91024501.pdf',
  },
  {
    id: 'log-003',
    timestampUtc: '2026-09-01T11:05:01Z',
    userId: 'usr-coord-01',
    userNome: 'Profª. Mariana Alcantara',
    userRole: 'COORDENADOR',
    action: 'DOCUMENT_REJECTION',
    resourceId: 'doc-c3',
    resourceTipo: 'Documento: Comprovante Residência (Carlos Eduardo)',
    ipAddress: '189.45.112.44',
    status: 'SUCCESS',
    detalhes: 'Recusa fundamentada: Documento emitido há mais de 180 dias. Notificação enviada ao aluno.',
    sha256Hash: '4b227777d4dd1fc61c6f884f48641d02b4d121d3fd328cb08b5531fcacdabf8a',
  },
  {
    id: 'log-004',
    timestampUtc: '2026-09-01T09:30:15Z',
    userId: 'usr-adm-01',
    userNome: 'Super Administrador DocFlow',
    userRole: 'SUPERADMIN',
    action: 'DOCUMENT_VIEW_REDACTED',
    resourceId: 'doc-rg-01',
    resourceTipo: 'Visualização Segura: RG com Tarja Protetora',
    ipAddress: '200.180.99.12',
    status: 'SUCCESS',
    detalhes: 'Inspeção de conformidade de armazenamento e integridade de chave.',
    sha256Hash: '9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08',
  },
  {
    id: 'log-005',
    timestampUtc: '2026-08-31T17:10:00Z',
    userId: 'usr-rh-01',
    userNome: 'Camila Peixoto (RH TechCorp)',
    userRole: 'COORDENADOR',
    action: 'DOSSIER_BULK_DOWNLOAD',
    resourceId: 'batch-turma-ti-01',
    resourceTipo: 'Lote de Dossiês: Turma DS-2026.1-A',
    ipAddress: '187.55.201.88',
    status: 'SUCCESS',
    detalhes: 'Exportação autorizada de 24 dossiês com status regular para arquivo corporativo.',
    sha256Hash: 'c7d2e3f4a5b67890123456789abcdef0123456789abcdef0123456789abcdef0',
  },
];
